import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const cvDir = scriptDir;
const contentDir = path.join(cvDir, 'content');

mkdirSync(contentDir, { recursive: true });

const template = readFile('cv.template.tex');

const sections = {
  researchAreas: renderResearchAreas(readMarkdown('research-areas.md')),
  employment: renderTabbedSection(readMarkdown('employment.md')),
  education: renderTabbedSection(readMarkdown('education.md')),
  publications: renderPublications(readMarkdown('publications.md')),
  services: renderLabeledBlock(readMarkdown('services.md')),
  teaching: renderLabeledBlock(readMarkdown('teaching.md')),
  industry: renderIndustry(readMarkdown('industry.md')),
};

const tex = template
  .replace('__RESEARCH_AREAS__', sections.researchAreas)
  .replace('__EMPLOYMENT__', sections.employment)
  .replace('__EDUCATION__', sections.education)
  .replace('__PUBLICATIONS__', sections.publications)
  .replace('__SERVICES__', sections.services)
  .replace('__TEACHING__', sections.teaching)
  .replace('__INDUSTRY__', sections.industry);

writeFileSync(
  path.join(cvDir, 'cv_tang.tex'),
  `%% Generated by build-cv.mjs. Do not edit directly.\n${tex}`,
);

function renderResearchAreas(markdown) {
  return parseParagraphs(markdown)
    .map((paragraph) => renderInline(paragraph))
    .join('\n\n');
}

function renderTabbedSection(markdown) {
  const items = parseBulletItems(markdown);
  const lines = [];

  for (const item of items) {
    const [label, value] = splitPipe(item.lines[0]);
    lines.push(`\\cvdated{${escapeTex(label)}}{${renderInline(value)}}`);

    for (const continuation of item.lines.slice(1)) {
      lines.push(`\\cvdetail{${renderInline(continuation)}}`);
    }
  }

  return lines.join('\n');
}

function renderPublications(markdown) {
  const items = parseBulletItems(markdown);
  const total = items.length;

  return items
    .map((item, index) => {
      const number = total - index;
      const [title, firstBody] = splitPipe(item.lines[0]);
      const bodyLines = [firstBody, ...item.lines.slice(1)].filter(Boolean);
      const renderedBody = bodyLines
        .map((line, lineIndex) => {
          const renderedLine = renderInline(line);
          if (lineIndex === 0) {
            return renderedLine.replaceAll(', ', ', \\allowbreak ');
          }
          return renderedLine;
        })
        .join('\\\\');

      return `\\cvpub{${number}}{${renderInline(title)}}{${renderedBody}}`;
    })
    .join('\n\n');
}

function renderLabeledBlock(markdown) {
  const sections = parseTitledBullets(markdown);
  const lines = [];

  sections.forEach((section, sectionIndex) => {
    lines.push(`\\cvsubsection{${renderInline(section.title)}}`);
    lines.push('\\begin{cvitemize}');
    section.items.forEach((item) => {
      const [label, value] = splitOptionalPipe(item.lines[0]);
      if (value !== null) {
        lines.push(`  \\item ${renderInline(label)} - ${renderInline(value)}`);
      } else {
        lines.push(`  \\item ${renderInline(label)}`);
      }
    });
    lines.push('\\end{cvitemize}');

    if (sectionIndex < sections.length - 1) {
      lines.push('');
    }
  });

  return lines.join('\n');
}

function renderIndustry(markdown) {
  const items = parseBulletItems(markdown);
  if (items.length !== 1) {
    throw new Error('industry.md must contain exactly one bullet item.');
  }

  const [role, period, project, mentor] = splitPipe(items[0].lines[0], 4);
  const description = items[0].lines.slice(1).join(' ');

  return `\\begin{tabularx}{\\textwidth}{@{}Y r@{}}
\\textbf{${renderInline(role)}} & ${renderInline(period)}\\\\
\\multicolumn{2}{@{}Y@{}}{\\textit{Project:} ${renderInline(project)} \\hfill \\textit{Mentor:} ${renderInline(mentor)}}\\\\
\\multicolumn{2}{@{}Y@{}}{${renderInline(description)}}
\\end{tabularx}`;
}

function parseParagraphs(markdown) {
  return markdown
    .trim()
    .split(/\n\s*\n/)
    .map((part) => part.replace(/\s+/g, ' ').trim())
    .filter(Boolean);
}

function parseBulletItems(markdown) {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n');
  const items = [];
  let current = null;

  for (const rawLine of lines) {
    const trimmed = rawLine.trimEnd();
    if (trimmed.trim() === '') {
      continue;
    }

    const bulletMatch = trimmed.match(/^-\s+(.*)$/);
    if (bulletMatch) {
      current = { lines: [bulletMatch[1].trim()] };
      items.push(current);
      continue;
    }

    if (/^\s{2,}\S/.test(rawLine) && current) {
      current.lines.push(rawLine.trim());
      continue;
    }

    throw new Error(`Unsupported markdown line: ${rawLine}`);
  }

  return items;
}

function parseTitledBullets(markdown) {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n');
  const sections = [];
  let currentSection = null;

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();
    if (trimmed === '') {
      continue;
    }

    const headingMatch = trimmed.match(/^###\s+(.*)$/);
    if (headingMatch) {
      currentSection = { title: headingMatch[1].trim(), items: [] };
      sections.push(currentSection);
      continue;
    }

    const bulletMatch = trimmed.match(/^-\s+(.*)$/);
    if (bulletMatch && currentSection) {
      currentSection.items.push({ lines: [bulletMatch[1].trim()] });
      continue;
    }

    throw new Error(`Unsupported markdown line: ${rawLine}`);
  }

  return sections;
}

function splitPipe(value, expectedParts = 2) {
  const parts = value.split('|').map((part) => part.trim());
  if (parts.length < expectedParts) {
    throw new Error(`Expected at least ${expectedParts} pipe-delimited parts in: ${value}`);
  }
  return parts;
}

function splitOptionalPipe(value) {
  const parts = value.split('|').map((part) => part.trim());
  if (parts.length === 1) {
    return [parts[0], null];
  }
  return [parts[0], parts.slice(1).join(' | ')];
}

function renderInline(value) {
  const escapes = [];
  let text = value.replace(/\\([\\|*`\[\]\(\)])/g, (_, character) => {
    const token = `@@ESC${escapes.length}@@`;
    escapes.push({ token, character });
    return token;
  });

  text = escapeTex(text);
  text = text.replace(/\*\*([^*]+)\*\*/g, '\\textbf{$1}');
  text = text.replace(/\*([^*]+)\*/g, '\\textit{$1}');
  text = text.replace(/`([^`]+)`/g, '\\texttt{\\small $1}');
  text = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '\\href{$2}{$1}');

  for (const { token, character } of escapes) {
    text = text.replaceAll(token, escapeTex(character));
  }

  return text;
}

function escapeTex(value) {
  return value
    .replaceAll('\\', '\\textbackslash{}')
    .replaceAll('&', '\\&')
    .replaceAll('%', '\\%')
    .replaceAll('$', '\\$')
    .replaceAll('#', '\\#')
    .replaceAll('_', '\\_')
    .replaceAll('{', '\\{')
    .replaceAll('}', '\\}')
    .replaceAll('~', '\\textasciitilde{}')
    .replaceAll('^', '\\textasciicircum{}');
}

function readMarkdown(file) {
  return readFileSync(path.join(contentDir, file), 'utf8').trim();
}

function readFile(file) {
  return readFileSync(path.join(cvDir, file), 'utf8');
}
